# This defines the ingress for the Ping Delegated Admin service

# NOTE: it will only work if an ingress controller (e.g. nginx) is running on
# your cluster.

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: pingcentral-ingress
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-private
spec:
  tls:
  - hosts:
    - pingcentral.${DNS_ZONE}
  rules:
  - host: pingcentral.${DNS_ZONE}
    http:
      paths:
      # This rule gives external access to the pingcentral service
      - path: /
        backend:
          serviceName: pingcentral
          servicePort: 9022
