kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
  - ${K8S_GIT_URL}/k8s-configs/cluster-tools/base/pod-reaper?ref=${K8S_GIT_BRANCH}

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pod-reaper-environment-variables
  behavior: merge
  envs:
  - env_vars