# A manual backup job - this does the same thing as the CronJob except it may be configured to be triggered in reaction
# to a ClickOps event.
apiVersion: batch/v1
kind: Job
metadata:
  name: pingdirectory-backup
  labels:
    app: ping-cloud
    role: pingdirectory
spec:
  ttlSecondsAfterFinished: 30
  backoffLimit: 5
  template:
    spec:
      serviceAccount: ping-serviceaccount
      restartPolicy: Never
      containers:
      - name: pingdirectory-backup
        image: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingdirectory/dev:v1.18-release-branch-latest
        imagePullPolicy: Always
        securityContext:
          runAsGroup: 9999
          runAsNonRoot: true
          runAsUser: 9031
          allowPrivilegeEscalation: false
        command:
        - /opt/in/backup.sh
        envFrom:
        - configMapRef:
            name: pingdirectory-environment-variables
        - configMapRef:
            name: pingcommon-environment-variables
        env:
        - name: LOG4J_FORMAT_MSG_NO_LOOKUPS
          value: "true"
        volumeMounts:
        - name: backup-script
          mountPath: /opt/in/backup.sh
          subPath: backup.sh
        - name: pd-backup-volume
          mountPath: /opt/out/backup
          subPath: backup
        - name: pd-backup-volume
          mountPath: /opt/out/backup-upload
          subPath: backup-upload
      volumes:
      - name: backup-script
        configMap:
          name: pingdirectory-backup
          defaultMode: 0555
      - name: pd-backup-volume
        persistentVolumeClaim:
          claimName: pingdirectory-backup

---
# Persistent Volume to run backup process
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pingdirectory-backup
  labels:
    class: pingdirectory-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: pingdirectory-enc-gp2
  resources:
    requests:
      storage: 40Gi