# NOTES: 
# - This custom patch is not applied to the cluster by default, 
#   adding this patch will expose all the private services to the public. 
#
# - Make sure WAF is enabled for all the public endpoints before applying 
#   this patch.
#

# This defines the ext ingress for the pingdelegator service

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ext-pingdelegator-ingress
  namespace: ${PING_CLOUD_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
  - hosts:
    - ext-pingdelegator.${DNS_ZONE}
  rules:
  - host: ext-pingdelegator.${DNS_ZONE}
    http:
      paths:
      - path: /
        backend:
          serviceName: pingdelegator
          servicePort: 1443
---
# This defines the ingress for the pingaccess-was admin service

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ext-pingaccess-was-admin-ingress
  namespace: ${PING_CLOUD_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
  - hosts:
    - ext-pingaccess-was-admin.${DNS_ZONE}
  rules:
  - host: ext-pingaccess-was-admin.${DNS_ZONE}
    http:
      paths:
      - path: /
        backend:
          serviceName: ext-pingaccess-was-admin
          servicePort: 9000
---
# This defines the private ingress for the pingaccess admin service

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ext-pingaccess-admin-ingress
  namespace: ${PING_CLOUD_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
    - hosts:
        - ext-pingaccess-admin-api.${DNS_ZONE}
  rules:
    - host: ext-pingaccess-admin-api.${DNS_ZONE}
      http:
        paths:
          - path: /
            backend:
              serviceName: pingaccess-admin
              servicePort: 9000
---
# This defines the private ingress for the pingfederate admin services.

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ext-pingfederate-admin-ingress
  namespace: ${PING_CLOUD_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
    - hosts:
        - ext-pingfederate-admin-api.${DNS_ZONE}
  rules:
    - host: ext-pingfederate-admin-api.${DNS_ZONE}
      http:
        paths:
          - path: /
            backend:
              serviceName: pingfederate-admin
              servicePort: pf-admin
---
# This defines the ingress for the pingdirectory REST API and SCIM service

apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ext-pingdirectory-http-ingress
  namespace: ${PING_CLOUD_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
  - hosts:
    - ext-pingdirectory.${DNS_ZONE}
  rules:
  - host: ext-pingdirectory.${DNS_ZONE}
    http:
      paths:
      - path: /
        backend:
          serviceName: pingdirectory-http
          servicePort: 1443
