kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- install.yaml
- custom-resource.yaml

patchesStrategicMerge:
  - |-
    $patch: delete
    apiVersion: admissionregistration.k8s.io/v1
    kind: ValidatingWebhookConfiguration
    metadata:
      name: ingress-nginx-admission
  - |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: ingress-nginx
  - |-
    $patch: delete
    apiVersion: rbac.authorization.k8s.io/v1
    kind: ClusterRoleBinding
    metadata:
      name: ingress-nginx-admission
