---
apiVersion: batch/v1beta1
kind: CronJob
metadata:
  labels:
    app: ping-cloud
  name: publish-core-dns-endpoints
  namespace: kube-system
spec:
  schedule: 0/15 * * * *
  jobTemplate:
    metadata:
      labels:
        app: publish-core-dns-endpoints
    spec:
      template:
        metadata:
          labels:
            app: publish-core-dns-endpoints
        spec:
          containers:
          - command: 
            - /bin/python3
            - /opt/publish_endpoints.py
            image: sthapa7/ping-cloud-aws:0.6
            name: publish-core-dns-endpoints
            envFrom:
              - configMapRef:
                  name: core-dns-environment-variables
            volumeMounts:
            - mountPath: /opt/publish_endpoints.py
              name: publish-core-dns-endpoints
              subPath: publish_endpoints.py
            - mountPath: /opt/core-dns-templates.zip
              name: core-dns-templates
              subPath: core-dns-templates.zip
            # We should be able to remove hostname-ip
            - mountPath: /opt/hostname-ip.txt
              name: hostname-ip
              subPath: hostname-ip.txt
          restartPolicy: OnFailure
          serviceAccount: kube-dns-serviceaccount
          volumes:
          - name: publish-core-dns-endpoints
            configMap:
              defaultMode: 365
              name: publish-core-dns-endpoints
          - name: core-dns-templates
            configMap:
              defaultMode: 365
              name: core-dns-templates
          # We should be able to remove hostname-ip
          - name: hostname-ip
            configMap:
              defaultMode: 365
              name: hostname-ip
          restartPolicy: OnFailure
          serviceAccount: kube-dns-serviceaccount
