# Sets up the storage class for the pingdatasync server (data and configuration)

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pingdatasync-gp2
provisioner: ebs.csi.aws.com
volumeBindingMode: WaitForFirstConsumer
parameters:
  encrypted: "true"
  type: gp2
  fsType: ext4
mountOptions:
  - discard
allowVolumeExpansion: true