apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "ping-cloud-${CLUSTER_STATE_REPO_BRANCH}-${REGION_NICK_NAME}"
  namespace: argocd
spec:
  syncPolicy:
    automated: {}
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s-configs/${CLUSTER_STATE_REPO_PATH}
    repoURL: ${CLUSTER_STATE_REPO_URL}
    targetRevision: ${CLUSTER_STATE_REPO_BRANCH}
    plugin:
      name: git-ops-command