# This defines the external ingress for the pingfederate admin services.

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingfederate-admin-ext-ingress
  namespace: ${PING_CLOUD_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
    - hosts:
        - ext-pingfederate-admin-api.${DNS_ZONE}
  rules:
    - host: ext-pingfederate-admin-api.${DNS_ZONE}
      http:
        paths:
          - path: /pf-admin-api/
            pathType: Prefix
            backend:
              service:
                name: pingfederate-admin
                port:
                  number: 9999