# A manual backup job - this does the same thing as the CronJob except it may be configured to be triggered in reaction
# to a ClickOps event.
apiVersion: batch/v1
kind: Job
metadata:
  name: pingdirectory-backup
  labels:
    app: ping-cloud
    role: pingdirectory
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 5
  template:
    spec:
      serviceAccount: ping-serviceaccount
      restartPolicy: Never
      containers:
      - name: pingdirectory-backup
        image: pingcloud-docker.jfrog.io/pingidentity/pingdirectory:2006.1-8.1.0.2
        command:
        - /opt/in/backup.sh
        env:
        - name: BACKUP_DIR
          value: /pd_backups
        envFrom:
        - configMapRef:
            name: pingdirectory-environment-variables
        volumeMounts:
        - name: passwords
          mountPath: /usr/local/secrets
          readOnly: true
        - name: backup-volume
          mountPath: /pd_backups
        - name: backup-script
          mountPath: /opt/in/backup.sh
          subPath: backup.sh
      volumes:
      - name: passwords
        secret:
          secretName: pingdirectory-passwords
          defaultMode: 0400
      - name: backup-script
        configMap:
          name: pingdirectory-backup
          defaultMode: 0555
      - name: backup-volume
        persistentVolumeClaim:
          claimName: pingdirectory-backup-pvc