apiVersion: v1
kind: ConfigMap
metadata:
  name: pingdirectory-restore
data:
  restore.sh: |
    #!/bin/sh
    set -e

    CURRENT_BACKUP_DIR=$(readlink -f /pd_backups/current)
    SERVER_BACKUP_DIR="${OUT_DIR}/restore"

    echo "Current backup contents:"
    ls ${CURRENT_BACKUP_DIR}

    echo "Installing kubectl"
    curl https://storage.googleapis.com/kubernetes-release/release/v1.15.0/bin/linux/amd64/kubectl -o /usr/local/bin/kubectl
    chmod +x /usr/local/bin/kubectl

    test -z "${BACKUP_RESTORE_POD}" && SERVER="${K8S_STATEFUL_SET_NAME}-0" || SERVER="${BACKUP_RESTORE_POD}"

    echo "Running restore script within ${SERVER} pod"
    echo "Copying backup from ${CURRENT_BACKUP_DIR} to ${SERVER}:${SERVER_BACKUP_DIR}"
    kubectl cp "${CURRENT_BACKUP_DIR}" "${SERVER}:${SERVER_BACKUP_DIR}" -c pingdirectory

    echo "Restoring to the latest backup under ${SERVER_BACKUP_DIR}"
    "${SERVER_BITS_DIR}/bin/restore" --task \
      --useSSL --trustAll \
      --hostname "${SERVER}.${K8S_STATEFUL_SET_SERVICE_NAME}" \
      --port ${LDAPS_PORT} \
      --bindDN "${ROOT_USER_DN}" \
      --bindPasswordFile "${ROOT_USER_PASSWORD_FILE}" \
      --backupDirectory "${SERVER_BACKUP_DIR}"

    echo "Removing backup directory ${SERVER}:${SERVER_BACKUP_DIR}"
    kubectl exec "${SERVER}" -c pingdirectory -- rm -rf "${SERVER_BACKUP_DIR}"

---

# A manual restore can be performed by deploying this job. It will restore
# data that was backed up by the periodic backup job to pingdirectory-0. All other servers
# must initialize the data from pingdirectory-0 via dsreplication initialize-all. This
# job can also be used to load the data initially from a backup created in
# another environment, e.g. dev.
apiVersion: batch/v1
kind: Job
metadata:
  name: pingdirectory-restore
  labels:
    app: ping-cloud
    role: pingdirectory
spec:
  ttlSecondsAfterFinished: 0
  backoffLimit: 5
  template:
    spec:
      serviceAccount: ping-serviceaccount
      restartPolicy: Never
      containers:
      - name: pingdirectory-restore
        image: pingcloud-docker.jfrog.io/pingidentity/pingdirectory:2006.1-8.1.0.2
        command:
        - /opt/in/restore.sh
        volumeMounts:
        - name: passwords
          mountPath: /usr/local/secrets
          readOnly: true
        - name: backup-volume
          mountPath: /pd_backups
        - name: restore-script
          mountPath: /opt/in/restore.sh
          subPath: restore.sh
        envFrom:
        - configMapRef:
            name: pingdirectory-environment-variables
      volumes:
      - name: passwords
        secret:
          secretName: pingdirectory-passwords
          defaultMode: 0400
      - name: restore-script
        configMap:
          name: pingdirectory-restore
          defaultMode: 0555
      - name: backup-volume
        persistentVolumeClaim:
          claimName: pingdirectory-backup-pvc