kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1


patchesStrategicMerge:

# pingcloud-metadata ingress
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: metadata-ingress
  patch: |
    - op: replace
      path: /spec/tls/0/hosts/0
      value: ext-pingdirectory.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: ext-pingdirectory.${DNS_ZONE}
