kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../k8s-configs/ping-cloud/test

configMapGenerator:
# Pingaccess
- name: pingaccess-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingaccess/env_vars

# Pingaccess WAS
- name: pingaccess-was-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingaccess-was/env_vars

# Pingfederate
- name: pingfederate-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingfederate/env_vars

# Pingdirectory
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - env_vars
  - pingdirectory/env_vars

patchesJson6902:

# pingdirectory HTTP
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingdirectory-http-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingdirectory${ENVIRONMENT}.${TENANT_DOMAIN}

    - op: replace
      path: /spec/rules/0/host
      value: pingdirectory${ENVIRONMENT}.${TENANT_DOMAIN}

# pingfederate runtime
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingfederate-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate${ENVIRONMENT}.${TENANT_DOMAIN}
    # PingFederate global ingress
    - op: add
      path: /spec/tls/0/hosts/-
      value: pf${ENVIRONMENT}.${GLOBAL_TENANT_DOMAIN}
    - op: add
      path: /spec/rules/-
      value:
        host: pf${ENVIRONMENT}.${GLOBAL_TENANT_DOMAIN}
        http:
          paths:
          # This rule gives external access to the global pingfederate runtime service
          - path: /
            backend:
              serviceName: pingfederate
              servicePort: 9031      

# pingfederate admin api
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingfederate-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingfederate-admin-api${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingfederate-admin-api${ENVIRONMENT}.${TENANT_DOMAIN}

# pingaccess runtime
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess${ENVIRONMENT}.${TENANT_DOMAIN}
    # PingAccess global ingress
    - op: add
      path: /spec/tls/0/hosts/-
      value: pa${ENVIRONMENT}.${GLOBAL_TENANT_DOMAIN}
    - op: add
      path: /spec/rules/-
      value:
        host: pa${ENVIRONMENT}.${GLOBAL_TENANT_DOMAIN}
        http:
          paths:
          # This rule gives external access to the global pingaccess runtime service
          - path: /
            backend:
              serviceName: pingaccess
              servicePort: 443

# pingaccess admin api
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-admin-api${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-admin-api${ENVIRONMENT}.${TENANT_DOMAIN}

# pingaccess agent
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-agent-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-agent${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-agent${ENVIRONMENT}.${TENANT_DOMAIN}

# pingaccess was admin
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-was-admin-ingress
  patch: |-
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-was-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-was-admin${ENVIRONMENT}.${TENANT_DOMAIN}

# pingaccess was runtime
- target:
    group: extensions
    version: v1beta1
    kind: Ingress
    name: pingaccess-was-ingress
  patch: |-
    # pingaccess admin through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingaccess-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/0/host
      value: pingaccess-admin${ENVIRONMENT}.${TENANT_DOMAIN}

    # pingfederate admin through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/1
      value: pingfederate-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/1/host
      value: pingfederate-admin${ENVIRONMENT}.${TENANT_DOMAIN}

    # Grafana through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/2
      value: monitoring${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/2/host
      value: monitoring${ENVIRONMENT}.${TENANT_DOMAIN}

    # Prometheus through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/3
      value: prometheus${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/3/host
      value: prometheus${ENVIRONMENT}.${TENANT_DOMAIN}

    # Kibana through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/4
      value: kibana${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: replace
      path: /spec/rules/4/host
      value: logs${ENVIRONMENT}.${TENANT_DOMAIN}

# Set a hostname for all the headless services so their endpoint IPs are published to Route53
- target:
    version: v1
    kind: Service
    name: pingdirectory
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingdirectory-cluster${ENVIRONMENT}.${TENANT_DOMAIN}

- target:
    version: v1
    kind: Service
    name: pingfederate-cluster
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingfederate-cluster${ENVIRONMENT}.${TENANT_DOMAIN}

- target:
    version: v1
    kind: Service
    name: pingaccess-admin
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingaccess-cluster${ENVIRONMENT}.${TENANT_DOMAIN}

- target:
    version: v1
    kind: Service
    name: pingaccess-was-admin
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingaccess-was-cluster${ENVIRONMENT}.${TENANT_DOMAIN}

# pingdirectory put ldaps on public and change the hostname
- target:
    version: v1
    kind: Service
    name: pingdirectory-admin
  patch: |-
    - op: replace
      path: /metadata/annotations/external-dns.alpha.kubernetes.io~1hostname
      value: pingdirectory-admin${ENVIRONMENT}.${TENANT_DOMAIN}
    - op: remove
      path: /metadata/annotations/service.beta.kubernetes.io~1aws-load-balancer-internal

patchesStrategicMerge:
- |-
  apiVersion: v1
  kind: Secret
  metadata:
    name: devops-secret
  data:
    PING_IDENTITY_DEVOPS_USER: ${PING_IDENTITY_DEVOPS_USER_BASE64}
    PING_IDENTITY_DEVOPS_KEY: ${PING_IDENTITY_DEVOPS_KEY_BASE64}
    GIT_USER: Z2l0bGFiLW1hY2hpbmUtdXNlci1hdC03MDUzNzA2MjE1Mzk=
    GIT_PASS: ZjNvd3dBSVkwYWpmZWwzWDMyUnFLeWZKS3ZEa3REZnJiUlBCQzhrY0wrcz0=

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: topology-descriptor
  data:
    descriptor.json: |-
      ${TOPOLOGY_DESCRIPTOR}
