apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "ping-cloud-${CLUSTER_STATE_REPO_BRANCH}-${TENANT_NAME}-${REGION_NICK_NAME}"
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/git-branch: ${CLUSTER_STATE_REPO_BRANCH}
    argocd-image-updater.argoproj.io/image-list: ${IMAGE_LIST}
    argocd-image-updater.argoproj.io/apps.update-strategy: latest
    argocd-image-updater.argoproj.io/apps.allow-tags: regexp:^${IMAGE_TAG_PREFIX}.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/argocd-image-updater-ssh-key
    argocd-image-updater.argoproj.io/write-back-target: kustomization
    notifications.argoproj.io/subscribe.on-sync-failed.slack: ${SLACK_CHANNEL}
    notifications.argoproj.io/subscribe.on-sync-status-unknown.slack: ${SLACK_CHANNEL}
spec:
  ignoreDifferences:
  - group: batch
    kind: Job
    jsonPointers:
    - /spec/ttlSecondsAfterFinished
  syncPolicy:
    automated:
      prune: true
  destination:
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s-configs/${REGION_NICK_NAME}
    repoURL: ${CLUSTER_STATE_REPO_URL}
    targetRevision: ${CLUSTER_STATE_REPO_BRANCH}
    plugin:
      name: git-ops-command
