### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###

### Always leave in at least this customization. Otherwise, kustomize will complain about an empty patch file. ###
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-environment-variables
  namespace: ping-cloud

---
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pingdirectory-gp2
parameters:
  encrypted: "true"
---
