### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###

### Always leave in at least this customization. Otherwise, kustomize will complain about an empty patch file. ###
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-environment-variables
  namespace: ping-cloud

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingdirectory
  namespace: ping-cloud
spec:
  volumeClaimTemplates:
    - metadata:
        name: out-dir
      spec:
        accessModes:
        - ReadWriteOnce
        storageClassName: pingdirectory-enc-gp2
        resources:
          requests:
            storage: 50Gi

---

