### PS/GSO customizations to OOTB resources should only go into this file. Otherwise, CSR auto-updates will break. ###

### Always leave in at least this customization. Otherwise, kustomize will complain about an empty patch file. ###
apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-environment-variables
  namespace: ping-cloud

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingcloud-metadata
  namespace: ping-cloud
spec:
  template:
    spec:
      containers:
      - name: pingcloud-metadata
        image: public.ecr.aws/r2h3l6e4/pingcloud-services/metadata:v1.0.5
        imagePullPolicy: Always
