apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: argocd-secret
  namespace: argocd
spec:
  encryptedData:
    admin.password: AgBBSJsJjVYcHdbNltbEOeZsyK/FcaR6Il56C0ePNKQPR/8UO+M785KOrCevRq+ZPzw3bc8JqhBBNyAufhO/FmR+MjrCzRaRVohbiHlzzxJxYnj83wBiOxWRTizlvCmi50L5B3eM/LFGmQJ/DHu3NTrYB+AGJO+kgC1GAAF1nemsPGRf1V+kwML9cG0gvmMN0xxJ9R7pOtff1top+UimpEK3azsyzmM05FrkBwvUXyOeAOZYEUSwKIVKBmFcOjxdHth04W9UxnYILOd5EZCYEHkGpDJjvdfrskmMTJUlHRpCXHNN/hpw2xiVnykobzyM/uIpX99lSs143NVnM8fFNxKjz50lr1etjxAM0sPX9fqNsHVJORroETivI1aXSO12Uy4u8FKolv/PM4Dl3Hnox3Xl6Wd9UBWkfwuqV6KmtIcUWIoppCTZM5KwtKAHD5rMaENdzNUCyReJ4kUhyXpBwIbVLleR/ymT7Abfsa344qr8zN+nGIqn1U5tgeLUdxABGy1JOVzXDOM/ZckQw2jnyG+p38cCdMC+SSqJv8nEGlJjVWz3KFXk5HN4M8nlr9szUP2I7dho5DE5BLmSUxCEbdI0HYzvXwamdHddzOuQTff4aDwYhHsLRzZ+LJ8lP39fZaak5geOQ0drGUuDPyXKptR/8g3ZvdxTr4Ut4ijJw47n25AVem/GbA76KPmuCg25PS+icuHs8bzszQ==
  template:
    metadata:
      annotations:
        sealedsecrets.bitnami.com/managed: "true"
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: argocd-secret
        app.kubernetes.io/part-of: argocd
      name: argocd-secret
      namespace: argocd
    type: Opaque

---
