---

### Ping app SSH private key ###

apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
data:
  id_rsa: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUF5QTFMRWl4RkhRU01TaHkwdmxMdHpmeUJCeTlHMUlMSS81NnBVbHJQeUlZWlhhdjJSR25oCm5LdlF5SDlGTnVmMGZDekJGV1VXZGZMUW9SV1hKc2pMK0NoTFF1Y25yY1BES2x2bGNOMTlvWHJEcFA2Yk1CM3p5QUpON08KblFqY3hTV2pHcFFUcHBEbS91cEpqaWEvaWs4M05GMEVUQWlLc3lOYWdMYk9hNXhRRmFQVTdjQ1ZtbEdZRXBYRG8xWUpvRApNaUtRdnRkWWI2ZnVGZTJnQ0ZsSC9BZ0tnNGpHRUMzTVVWMWh5SjA1cnA4TkN3YWtwcU1xZUY0c2hvenE2ZVI1RmNVZUhXCmFaUnBxTWhyYWhHQVB6eFZWbnVLakpuVzE1MFZsd2MrbUd5SVM3cHlyQWxxMUZmU0pubWNDNi8vRmVEVFFTQnB3STdodmIKRWYraGlpNnFvUUFBQTlBVExpc3NFeTRyTEFBQUFBZHpjMmd0Y25OaEFBQUJBUURJRFVzU0xFVWRCSXhLSExTK1V1M04vSQpFSEwwYlVnc2ovbnFsU1dzL0loaGxkcS9aRWFlR2NxOURJZjBVMjUvUjhMTUVWWlJaMTh0Q2hGWmNteU12NEtFdEM1eWV0Cnc4TXFXK1Z3M1gyaGVzT2svcHN3SGZQSUFrM3M2ZENOekZKYU1hbEJPbWtPYis2a21PSnIrS1R6YzBYUVJNQ0lxekkxcUEKdHM1cm5GQVZvOVR0d0pXYVVaZ1NsY09qVmdtZ015SXBDKzExaHZwKzRWN2FBSVdVZjhDQXFEaU1ZUUxjeFJYV0hJblRtdQpudzBMQnFTbW95cDRYaXlHak9ycDVIa1Z4UjRkWnBsR21veUd0cUVZQS9QRlZXZTRxTW1kYlhuUldYQno2WWJJaEx1bktzCkNXclVWOUltZVp3THIvOFY0Tk5CSUduQWp1RzlzUi82R0tMcXFoQUFBQUF3RUFBUUFBQVFCWmJSZlIxOWhOVUdzbDlnOFYKeFJ4b3FDZEZmdXk2c253SFNIV0lTdS8zUTNxelZOdVJXWU53OVowdkF6VjloZExVYjIwZ2t6K25HaFFJN2czVFdJOVZMeQozMWlqOUNmZkFRVDJRUlAvR1k3YmZuV2FrbHFUNEFlb2M3RUlvWjJPdzNSVnZUdkxpWnE0K1NKSVdTbm1PZU1EbFZFR2JBCnNVYVFsYjRGd0YzcW9oV3ZlVzZkVklhc2UyT3pmZnVuMEVlSDhxYXUwbzF2OTh2UFFiS28xSzVaTTNZK2xjMU11V0x0d2cKcnVKRUFMdXV1UjhjbmIxS0NvK2dDeVZmK1U2ZVZiVi83Z0hzVXIxWXJaajBuS0pWUXIvaW4zMDhpU2V4QVNTSkduMnpjZQpWWEdHc3kwWlFEK0UrclRPUDkrWEc5TlZPbmtMTGticmlGZ3VLalpNRkREQkFBQUFnUURkb292ME5uNndNQ0pjZWV6aGlFCnlsbW1CaVNqUUEyVnNVeXoxUEJuN2dMUkIxVjBNYmY5dGRuZ0dMS2hDRjBXSVBpdm1Tb1dpQ0RSQ1FkOERJTW52T1hiYlIKVEZkTEJRek1mTHFXUWNocDE2bm4yWWZabnh5Q3B1dVJ2Zlk3OHlFVmZMVVV1SkdnSkZZYTlyQ1d4MDVYamsrUVRpL2JVbAowaWNoQ0N2UDloandBQUFJRUE2cWN0Y3RpRXNNbFQ5MmVxRWs0bUpVaEJOVExEa2pBVXpFQmFHS3JBdThCY2xhaldmNjZMCkxkeDQwa1o1dWhDbmxHRENLWUxkd1QzT3JuSEJMOHNueHYwdFJ6VWZLQlIxSUQ5WTFlSTY2cFRpZi85b28wZHlNTk1Pb0YKODVmei9HNlk0TXFQdysrWVFqUzh1SCtpYld2RzcyL2JTWlk0MlF1MGN6d0JjK05tTUFBQUNCQU5wQVN0QUk5Uk9mYnVnQQoyaHN4RzRLSy8wb3lnL0Fyck9VWDNydHNvYlo1dTBLa24yK2F3c2QvNVFzK0RtY0NpWU4xVFF2ZVMvRnR4M2s0UUFvbzNGCmdDaG8yUzM0T1BCM0c5Ui9RWDMydS9MY2pwZ1pSUW93bzlhYTFuTkpVVkpTVUtyUE1BekZDdVB3N2RSOTlFUGVuQXlybnoKYnBCMWhhT1VodzJUU05nckFBQUFGM04xY21GcWRHaGhjR0ZBYzNWeVlXcDBhR0Z3WVMxeUFRSUQKLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==

---

# NewRelic license key to send APM data
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: newrelic-license-key
data:
  NEW_RELIC_LICENSE_KEY: NTE5MGVmNzZiZTRlZjhmZjhkYmE1NTBjZDZjODk4NzUxZWUzTlJBTA==

---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nr-license-key
  namespace: elastic-stack-logging
data:
  NEW_RELIC_LICENSE_KEY: NTE5MGVmNzZiZTRlZjhmZjhkYmE1NTBjZDZjODk4NzUxZWUzTlJBTA==

# ---
# ### Optional certificate(s) to add to the PD truststore ###
# apiVersion: v1
# kind: Secret
# type: Opaque
# metadata:
#  name: pingdirectory-truststore-certs
# data:
#  cert_one: |
#    asdfasdf
#  cert_two: |
#    asdfasdf

---

### Licenses ###

# Add PingDirectory.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingdirectory-license
type: Opaque

---

# Add pingfederate.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingfederate-license
type: Opaque

---

# Add pingaccess.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingaccess-license
type: Opaque

---

# Add pingaccess.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingaccess-was-license
type: Opaque

---

### Product passwords ###

# Supported keys:
# Exported as environment variables: PF_ADMIN_USER_PASSWORD, PF_LDAP_PASSWORD, DA_OAUTH_TOKEN_VALIDATOR_SECRET, PC_ADMIN_USER_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcommon-passwords

---

# Supported keys:
# Mounted as files: root-user-password, admin-user-password, encryption-password, encryption-settings.pin, ads.crt, ads.key
# Exported as environment variables: P14C_ENVIRONMENT_ID, P14C_CLIENT_ID, P14C_CLIENT_SECRET
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingdirectory-passwords

---

# Supported keys:
# Mounted as file: root-user-password
# Exported as environment variable: ROOT_USER_PASSWORD, EXT_PD_SYNC_BIND_DN_PASSWORD, EXT_PD_ADMIN_BIND_DN_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingdatasync-passwords

---

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-passwords

---

# Supported keys:
# Exported as environment variables: PA_ADMIN_USER_PASSWORD, OLD_PA_ADMIN_USER_PASSWORD,
#                                    P14C_ISSUER, P14C_CLIENT_ID, P14C_CLIENT_SECRET
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingaccess-was-passwords

---

# Supported keys:
# Exported as environment variables: HEALTHCHECK_USER_NAME, HEALTHCHECK_USER_PASSWORD
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: healthcheck-user
  namespace: health

# %% NOTE: Below secrets are for the Developer CDE only (when IS_BELUGA_ENV is 'true') to make sure Argo works properly %%#
---

### Argo CD ###

# Deploy the git key of the CD tool to the cluster state repo
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argo-git-deploy
  namespace: argocd
data:
  identity: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUF5QTFMRWl4RkhRU01TaHkwdmxMdHpmeUJCeTlHMUlMSS81NnBVbHJQeUlZWlhhdjJSR25oCm5LdlF5SDlGTnVmMGZDekJGV1VXZGZMUW9SV1hKc2pMK0NoTFF1Y25yY1BES2x2bGNOMTlvWHJEcFA2Yk1CM3p5QUpON08KblFqY3hTV2pHcFFUcHBEbS91cEpqaWEvaWs4M05GMEVUQWlLc3lOYWdMYk9hNXhRRmFQVTdjQ1ZtbEdZRXBYRG8xWUpvRApNaUtRdnRkWWI2ZnVGZTJnQ0ZsSC9BZ0tnNGpHRUMzTVVWMWh5SjA1cnA4TkN3YWtwcU1xZUY0c2hvenE2ZVI1RmNVZUhXCmFaUnBxTWhyYWhHQVB6eFZWbnVLakpuVzE1MFZsd2MrbUd5SVM3cHlyQWxxMUZmU0pubWNDNi8vRmVEVFFTQnB3STdodmIKRWYraGlpNnFvUUFBQTlBVExpc3NFeTRyTEFBQUFBZHpjMmd0Y25OaEFBQUJBUURJRFVzU0xFVWRCSXhLSExTK1V1M04vSQpFSEwwYlVnc2ovbnFsU1dzL0loaGxkcS9aRWFlR2NxOURJZjBVMjUvUjhMTUVWWlJaMTh0Q2hGWmNteU12NEtFdEM1eWV0Cnc4TXFXK1Z3M1gyaGVzT2svcHN3SGZQSUFrM3M2ZENOekZKYU1hbEJPbWtPYis2a21PSnIrS1R6YzBYUVJNQ0lxekkxcUEKdHM1cm5GQVZvOVR0d0pXYVVaZ1NsY09qVmdtZ015SXBDKzExaHZwKzRWN2FBSVdVZjhDQXFEaU1ZUUxjeFJYV0hJblRtdQpudzBMQnFTbW95cDRYaXlHak9ycDVIa1Z4UjRkWnBsR21veUd0cUVZQS9QRlZXZTRxTW1kYlhuUldYQno2WWJJaEx1bktzCkNXclVWOUltZVp3THIvOFY0Tk5CSUduQWp1RzlzUi82R0tMcXFoQUFBQUF3RUFBUUFBQVFCWmJSZlIxOWhOVUdzbDlnOFYKeFJ4b3FDZEZmdXk2c253SFNIV0lTdS8zUTNxelZOdVJXWU53OVowdkF6VjloZExVYjIwZ2t6K25HaFFJN2czVFdJOVZMeQozMWlqOUNmZkFRVDJRUlAvR1k3YmZuV2FrbHFUNEFlb2M3RUlvWjJPdzNSVnZUdkxpWnE0K1NKSVdTbm1PZU1EbFZFR2JBCnNVYVFsYjRGd0YzcW9oV3ZlVzZkVklhc2UyT3pmZnVuMEVlSDhxYXUwbzF2OTh2UFFiS28xSzVaTTNZK2xjMU11V0x0d2cKcnVKRUFMdXV1UjhjbmIxS0NvK2dDeVZmK1U2ZVZiVi83Z0hzVXIxWXJaajBuS0pWUXIvaW4zMDhpU2V4QVNTSkduMnpjZQpWWEdHc3kwWlFEK0UrclRPUDkrWEc5TlZPbmtMTGticmlGZ3VLalpNRkREQkFBQUFnUURkb292ME5uNndNQ0pjZWV6aGlFCnlsbW1CaVNqUUEyVnNVeXoxUEJuN2dMUkIxVjBNYmY5dGRuZ0dMS2hDRjBXSVBpdm1Tb1dpQ0RSQ1FkOERJTW52T1hiYlIKVEZkTEJRek1mTHFXUWNocDE2bm4yWWZabnh5Q3B1dVJ2Zlk3OHlFVmZMVVV1SkdnSkZZYTlyQ1d4MDVYamsrUVRpL2JVbAowaWNoQ0N2UDloandBQUFJRUE2cWN0Y3RpRXNNbFQ5MmVxRWs0bUpVaEJOVExEa2pBVXpFQmFHS3JBdThCY2xhaldmNjZMCkxkeDQwa1o1dWhDbmxHRENLWUxkd1QzT3JuSEJMOHNueHYwdFJ6VWZLQlIxSUQ5WTFlSTY2cFRpZi85b28wZHlNTk1Pb0YKODVmei9HNlk0TXFQdysrWVFqUzh1SCtpYld2RzcyL2JTWlk0MlF1MGN6d0JjK05tTUFBQUNCQU5wQVN0QUk5Uk9mYnVnQQoyaHN4RzRLSy8wb3lnL0Fyck9VWDNydHNvYlo1dTBLa24yK2F3c2QvNVFzK0RtY0NpWU4xVFF2ZVMvRnR4M2s0UUFvbzNGCmdDaG8yUzM0T1BCM0c5Ui9RWDMydS9MY2pwZ1pSUW93bzlhYTFuTkpVVkpTVUtyUE1BekZDdVB3N2RSOTlFUGVuQXlybnoKYnBCMWhhT1VodzJUU05nckFBQUFGM04xY21GcWRHaGhjR0ZBYzNWeVlXcDBhR0Z3WVMxeUFRSUQKLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==
---
# Add argocd admin password to the data section with the bcrypt hash value.
# Ref: https://argo-cd.readthedocs.io/en/stable/faq/#i-forgot-the-admin-password-how-do-i-reset-it
apiVersion: v1
kind: Secret
metadata:
  name: argocd-secret
type: Opaque
data:
  admin.password: "JDJhJDEwJHlWRU5GT21mTzBGcXNLNlVreTBEei5vLzM1ekloWDdmMjBvOU9CRVFKNVZqWUpOUHhGbUNlCg=="
---
### Ping app SSH private key ###
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: ssh-id-key-secret
data:
  id_rsa: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUF5QTFMRWl4RkhRU01TaHkwdmxMdHpmeUJCeTlHMUlMSS81NnBVbHJQeUlZWlhhdjJSR25oCm5LdlF5SDlGTnVmMGZDekJGV1VXZGZMUW9SV1hKc2pMK0NoTFF1Y25yY1BES2x2bGNOMTlvWHJEcFA2Yk1CM3p5QUpON08KblFqY3hTV2pHcFFUcHBEbS91cEpqaWEvaWs4M05GMEVUQWlLc3lOYWdMYk9hNXhRRmFQVTdjQ1ZtbEdZRXBYRG8xWUpvRApNaUtRdnRkWWI2ZnVGZTJnQ0ZsSC9BZ0tnNGpHRUMzTVVWMWh5SjA1cnA4TkN3YWtwcU1xZUY0c2hvenE2ZVI1RmNVZUhXCmFaUnBxTWhyYWhHQVB6eFZWbnVLakpuVzE1MFZsd2MrbUd5SVM3cHlyQWxxMUZmU0pubWNDNi8vRmVEVFFTQnB3STdodmIKRWYraGlpNnFvUUFBQTlBVExpc3NFeTRyTEFBQUFBZHpjMmd0Y25OaEFBQUJBUURJRFVzU0xFVWRCSXhLSExTK1V1M04vSQpFSEwwYlVnc2ovbnFsU1dzL0loaGxkcS9aRWFlR2NxOURJZjBVMjUvUjhMTUVWWlJaMTh0Q2hGWmNteU12NEtFdEM1eWV0Cnc4TXFXK1Z3M1gyaGVzT2svcHN3SGZQSUFrM3M2ZENOekZKYU1hbEJPbWtPYis2a21PSnIrS1R6YzBYUVJNQ0lxekkxcUEKdHM1cm5GQVZvOVR0d0pXYVVaZ1NsY09qVmdtZ015SXBDKzExaHZwKzRWN2FBSVdVZjhDQXFEaU1ZUUxjeFJYV0hJblRtdQpudzBMQnFTbW95cDRYaXlHak9ycDVIa1Z4UjRkWnBsR21veUd0cUVZQS9QRlZXZTRxTW1kYlhuUldYQno2WWJJaEx1bktzCkNXclVWOUltZVp3THIvOFY0Tk5CSUduQWp1RzlzUi82R0tMcXFoQUFBQUF3RUFBUUFBQVFCWmJSZlIxOWhOVUdzbDlnOFYKeFJ4b3FDZEZmdXk2c253SFNIV0lTdS8zUTNxelZOdVJXWU53OVowdkF6VjloZExVYjIwZ2t6K25HaFFJN2czVFdJOVZMeQozMWlqOUNmZkFRVDJRUlAvR1k3YmZuV2FrbHFUNEFlb2M3RUlvWjJPdzNSVnZUdkxpWnE0K1NKSVdTbm1PZU1EbFZFR2JBCnNVYVFsYjRGd0YzcW9oV3ZlVzZkVklhc2UyT3pmZnVuMEVlSDhxYXUwbzF2OTh2UFFiS28xSzVaTTNZK2xjMU11V0x0d2cKcnVKRUFMdXV1UjhjbmIxS0NvK2dDeVZmK1U2ZVZiVi83Z0hzVXIxWXJaajBuS0pWUXIvaW4zMDhpU2V4QVNTSkduMnpjZQpWWEdHc3kwWlFEK0UrclRPUDkrWEc5TlZPbmtMTGticmlGZ3VLalpNRkREQkFBQUFnUURkb292ME5uNndNQ0pjZWV6aGlFCnlsbW1CaVNqUUEyVnNVeXoxUEJuN2dMUkIxVjBNYmY5dGRuZ0dMS2hDRjBXSVBpdm1Tb1dpQ0RSQ1FkOERJTW52T1hiYlIKVEZkTEJRek1mTHFXUWNocDE2bm4yWWZabnh5Q3B1dVJ2Zlk3OHlFVmZMVVV1SkdnSkZZYTlyQ1d4MDVYamsrUVRpL2JVbAowaWNoQ0N2UDloandBQUFJRUE2cWN0Y3RpRXNNbFQ5MmVxRWs0bUpVaEJOVExEa2pBVXpFQmFHS3JBdThCY2xhaldmNjZMCkxkeDQwa1o1dWhDbmxHRENLWUxkd1QzT3JuSEJMOHNueHYwdFJ6VWZLQlIxSUQ5WTFlSTY2cFRpZi85b28wZHlNTk1Pb0YKODVmei9HNlk0TXFQdysrWVFqUzh1SCtpYld2RzcyL2JTWlk0MlF1MGN6d0JjK05tTUFBQUNCQU5wQVN0QUk5Uk9mYnVnQQoyaHN4RzRLSy8wb3lnL0Fyck9VWDNydHNvYlo1dTBLa24yK2F3c2QvNVFzK0RtY0NpWU4xVFF2ZVMvRnR4M2s0UUFvbzNGCmdDaG8yUzM0T1BCM0c5Ui9RWDMydS9MY2pwZ1pSUW93bzlhYTFuTkpVVkpTVUtyUE1BekZDdVB3N2RSOTlFUGVuQXlybnoKYnBCMWhhT1VodzJUU05nckFBQUFGM04xY21GcWRHaGhjR0ZBYzNWeVlXcDBhR0Z3WVMxeUFRSUQKLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==
---
### Argo CD Image Updater  ###

# Deploy the git key for argocd-image-updater
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-image-updater-ssh-key
  namespace: argocd
data:
  sshPrivateKey: |
    LS0tLS1CRUdJTiBPUEVOU1NIIFBSSVZBVEUgS0VZLS0tLS0KYjNCbGJuTnphQzFyWlhrdGRqRUFBQUFBQkc1dmJtVUFBQUFFYm05dVpRQUFBQUFBQUFBQkFBQUJGd0FBQUFkemMyZ3RjbgpOaEFBQUFBd0VBQVFBQUFRRUF5QTFMRWl4RkhRU01TaHkwdmxMdHpmeUJCeTlHMUlMSS81NnBVbHJQeUlZWlhhdjJSR25oCm5LdlF5SDlGTnVmMGZDekJGV1VXZGZMUW9SV1hKc2pMK0NoTFF1Y25yY1BES2x2bGNOMTlvWHJEcFA2Yk1CM3p5QUpON08KblFqY3hTV2pHcFFUcHBEbS91cEpqaWEvaWs4M05GMEVUQWlLc3lOYWdMYk9hNXhRRmFQVTdjQ1ZtbEdZRXBYRG8xWUpvRApNaUtRdnRkWWI2ZnVGZTJnQ0ZsSC9BZ0tnNGpHRUMzTVVWMWh5SjA1cnA4TkN3YWtwcU1xZUY0c2hvenE2ZVI1RmNVZUhXCmFaUnBxTWhyYWhHQVB6eFZWbnVLakpuVzE1MFZsd2MrbUd5SVM3cHlyQWxxMUZmU0pubWNDNi8vRmVEVFFTQnB3STdodmIKRWYraGlpNnFvUUFBQTlBVExpc3NFeTRyTEFBQUFBZHpjMmd0Y25OaEFBQUJBUURJRFVzU0xFVWRCSXhLSExTK1V1M04vSQpFSEwwYlVnc2ovbnFsU1dzL0loaGxkcS9aRWFlR2NxOURJZjBVMjUvUjhMTUVWWlJaMTh0Q2hGWmNteU12NEtFdEM1eWV0Cnc4TXFXK1Z3M1gyaGVzT2svcHN3SGZQSUFrM3M2ZENOekZKYU1hbEJPbWtPYis2a21PSnIrS1R6YzBYUVJNQ0lxekkxcUEKdHM1cm5GQVZvOVR0d0pXYVVaZ1NsY09qVmdtZ015SXBDKzExaHZwKzRWN2FBSVdVZjhDQXFEaU1ZUUxjeFJYV0hJblRtdQpudzBMQnFTbW95cDRYaXlHak9ycDVIa1Z4UjRkWnBsR21veUd0cUVZQS9QRlZXZTRxTW1kYlhuUldYQno2WWJJaEx1bktzCkNXclVWOUltZVp3THIvOFY0Tk5CSUduQWp1RzlzUi82R0tMcXFoQUFBQUF3RUFBUUFBQVFCWmJSZlIxOWhOVUdzbDlnOFYKeFJ4b3FDZEZmdXk2c253SFNIV0lTdS8zUTNxelZOdVJXWU53OVowdkF6VjloZExVYjIwZ2t6K25HaFFJN2czVFdJOVZMeQozMWlqOUNmZkFRVDJRUlAvR1k3YmZuV2FrbHFUNEFlb2M3RUlvWjJPdzNSVnZUdkxpWnE0K1NKSVdTbm1PZU1EbFZFR2JBCnNVYVFsYjRGd0YzcW9oV3ZlVzZkVklhc2UyT3pmZnVuMEVlSDhxYXUwbzF2OTh2UFFiS28xSzVaTTNZK2xjMU11V0x0d2cKcnVKRUFMdXV1UjhjbmIxS0NvK2dDeVZmK1U2ZVZiVi83Z0hzVXIxWXJaajBuS0pWUXIvaW4zMDhpU2V4QVNTSkduMnpjZQpWWEdHc3kwWlFEK0UrclRPUDkrWEc5TlZPbmtMTGticmlGZ3VLalpNRkREQkFBQUFnUURkb292ME5uNndNQ0pjZWV6aGlFCnlsbW1CaVNqUUEyVnNVeXoxUEJuN2dMUkIxVjBNYmY5dGRuZ0dMS2hDRjBXSVBpdm1Tb1dpQ0RSQ1FkOERJTW52T1hiYlIKVEZkTEJRek1mTHFXUWNocDE2bm4yWWZabnh5Q3B1dVJ2Zlk3OHlFVmZMVVV1SkdnSkZZYTlyQ1d4MDVYamsrUVRpL2JVbAowaWNoQ0N2UDloandBQUFJRUE2cWN0Y3RpRXNNbFQ5MmVxRWs0bUpVaEJOVExEa2pBVXpFQmFHS3JBdThCY2xhaldmNjZMCkxkeDQwa1o1dWhDbmxHRENLWUxkd1QzT3JuSEJMOHNueHYwdFJ6VWZLQlIxSUQ5WTFlSTY2cFRpZi85b28wZHlNTk1Pb0YKODVmei9HNlk0TXFQdysrWVFqUzh1SCtpYld2RzcyL2JTWlk0MlF1MGN6d0JjK05tTUFBQUNCQU5wQVN0QUk5Uk9mYnVnQQoyaHN4RzRLSy8wb3lnL0Fyck9VWDNydHNvYlo1dTBLa24yK2F3c2QvNVFzK0RtY0NpWU4xVFF2ZVMvRnR4M2s0UUFvbzNGCmdDaG8yUzM0T1BCM0c5Ui9RWDMydS9MY2pwZ1pSUW93bzlhYTFuTkpVVkpTVUtyUE1BekZDdVB3N2RSOTlFUGVuQXlybnoKYnBCMWhhT1VodzJUU05nckFBQUFGM04xY21GcWRHaGhjR0ZBYzNWeVlXcDBhR0Z3WVMxeUFRSUQKLS0tLS1FTkQgT1BFTlNTSCBQUklWQVRFIEtFWS0tLS0tCg==
---
#Argocd slack token
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: argocd-notifications-secret
data:
  slack-token: eG94Yi0yNjI3MTI5OTQwLTIxMDkwMjg2MzkxNTMtSmJYdDZEMmtwd0tzYmRNUmgyTEtTZDhx
---
# Add argocd admin password for argocd-image-updater.
apiVersion: v1
kind: Secret
metadata:
  name: argocd-image-updater-secret
data:
  argocd.token: "JDJhJDEwJHlWRU5GT21mTzBGcXNLNlVreTBEei5vLzM1ekloWDdmMjBvOU9CRVFKNVZqWUpOUHhGbUNlCg=="
---
# Slack token to send argo events notification
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: slack-secret
  namespace: argo-events
data:
  token: eG94Yi0yNjI3MTI5OTQwLTIxMDkwMjg2MzkxNTMtSmJYdDZEMmtwd0tzYmRNUmgyTEtTZDhx
---
# NewRelic license key to send APM data
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: newrelic-license-key
data:
  NEW_RELIC_LICENSE_KEY: NTE5MGVmNzZiZTRlZjhmZjhkYmE1NTBjZDZjODk4NzUxZWUzTlJBTA==
---
# In order to change the PingCentral admin password, 2 rollouts are necessary. 
#
# 1. On the 1st rollout, change the PC_ADMIN_USER_PASSWORD as appropriate and the 
#    LAST_UPDATE_REASON for PingCentral. This will cause a rollout/restart of
#    the PingCentral pod.
# 2. On the 2nd rollout, change the OLD_PC_ADMIN_USER_PASSWORD to match the 
#.   PC_ADMIN_USER_PASSWORD. This will cause an update of the secret. 
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingcentral-passwords
---
### Licenses ###

# Add pingcentral.lic (case-sensitive) to the data section with the base64-encoded value of the license file
apiVersion: v1
kind: Secret
metadata:
  name: pingcentral-license
type: Opaque
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: nr-license-key
  namespace: elastic-stack-logging
data:
  NEW_RELIC_LICENSE_KEY: NTE5MGVmNzZiZTRlZjhmZjhkYmE1NTBjZDZjODk4NzUxZWUzTlJBTA==

# %% END automatically appended secrets from generate-cluster-state.sh
