########################################################################################################################
# Customer parameters that are shared by multiple apps
########################################################################################################################

########################################################
# Multi-region parameters
########################################################
isMultiCluster: false

# primaryRegion is the primary AWS region name
# the primary region should have the same value for region and primaryRegion
primaryRegion: "us-east-2"

# primaryDnsZone is the primary dns zone for customer for region
primaryDnsZone: "mulloway1.us1.ping-preview.cloud"

# primaryTenantDomain is the primary domain suffix for customer for region
# the primary region should have the same value for tenantDomain and primaryTenantDomain
primaryTenantDomain: "mulloway1.us1.ping-preview.cloud"

# secondaryTenantDomains is an optional comma-separated list of the tenant domain suffixes of secondary regions used
# for PingFederate adaptive clustering using the JGroups DNS_PING discovery protocol:
#
#   - Do NOT include the primary tenant domain in the list
#   - Do NOT include the CDE prefix in the domain name
#
# For example, if the primary domain is "tuna.us1.ping-preview.cloud", then set it
# to "tuna.eu1.ping-preview.cloud,tuna.au1.ping-preview.cloud" to specify secondary
# domains in regions eu1 and au1.
#
# NOTES:
#   - Only used in multi-cluster environments. If provided, PF will be configured with DNS_PING.
#   - It is recommended that SECONDARY_TENANT_DOMAINS be set apriori, even before the
#     secondary regions are created to avoid pod rollouts. DNS_PING will simply ignore
#     unreachable domains. If it is not set beforehand, then all servers in the PF
#     cluster (admin and engines) must be re-rolled to pick up the change.
secondaryTenantDomains: ""

# globalTenantDomain is the region-independent URL used for DNS failover/routing
globalTenantDomain: "global.mulloway1.ping-preview.cloud"


########################################################
# S3 buckets
########################################################
# pingArtifactRepoUrl is the ping-hosted common artifacts URL
pingArtifactRepoUrl: "https://ping-artifacts.s3-us-west-2.amazonaws.com"

# logArchiveUrl is the customer-specific log URL for region
logArchiveUrl: "ssm://pcpt/service/storage/logs/uri"

# backupUrl is the customer-specific backup URL for region
backupUrl: "ssm://pcpt/service/storage/backup/uri"


########################################################
# Miscellaneous ping-cloud-base variables
########################################################
# pingCloudNamespace is the namespace where Ping apps are deployed
pingCloudNamespace: "ping-cloud"

# k8sGitUrl is the ping-cloud-base git URL for base Kubernetes manifests
k8sGitUrl: "https://github.com/pingidentity/ping-cloud-base"

# k8sGitBranch is the ping-cloud-base git branch for base Kubernetes manifests
k8sGitBranch: "v1.18-release-branch"

# ecrRegistryName is the name of the Docker image registry
ecrRegistryName: "public.ecr.aws/r2h3l6e4"

# ecr_env is the suffix used to denote to use dev image repositories
ecrEnv: "/dev"

# clusterName is the eks cluster name
clusterName: "mulloway1"

# serverProfileUrl is the git URL for the profile repo
serverProfileUrl: "https://github.com/sura8257/profile-repo"

# serverProfileBranch is the git branch for the profile repo
serverProfileBranch: "stage"

# userBaseDN is the variable used by Ping products
userBaseDN: "dc=example,dc=com"

# Multiple Backend IDs
userBackendId2: "userRoot_2"
userBackendId3: "userRoot_3"
userBackendId4: "userRoot_4"
userBackendId5: "userRoot_5"


# Multiple Backend IDs Base DNs
userBaseDN2: ""
userBaseDN3: ""
userBaseDN4: ""
userBaseDN5: ""

########################################################
# Environment-specific variables
########################################################
# environmentType is used by server profile hooks
environmentType: "stage"

# env is used by Kubernetes manifests
env: "stage"

isBelugaEnv: true


########################################################
# DevOps License environment variables
########################################################
pingIdentityDevopsUser: "ssm://pcpt/devops-license/user"
pingIdentityDevopsKey: "ssm://pcpt/devops-license/key"


########################################################
# Ping image tags
########################################################
pingaccessImageTag: "v1.18-release-branch-latest"
pingaccessWasImageTag: "v1.18-release-branch-latest"
pingfederateImageTag: "v1.18-release-branch-latest"
pingdirectoryImageTag: "v1.18-release-branch-latest"
pingdelegatorImageTag: "v1.18-release-branch-latest"
pingcentralImageTag: "v1.18-release-branch-latest"
pingdatasyncImageTag: "v1.18-release-branch-latest"
metadataImageTag: "v1.18-release-branch-latest"
bootstrapImageTag: "v1.18-release-branch-latest"
healthcheckImageTag: "v1.18-release-branch-latest"
p14cIntegrationImageTag: "v1.18-release-branch-latest"


########################################################
# Public hostnames
########################################################
pdPrimaryPublicHostname: "pingdirectory-admin.${PRIMARY_TENANT_DOMAIN}"
pfAdminPublicHostname: "pingfederate-admin.${PRIMARY_TENANT_DOMAIN}"
pfAdminApiPublicHostname: "pingfederate-admin-api.${PRIMARY_TENANT_DOMAIN}"
paAdminPublicHostname: "pingaccess-admin.${PRIMARY_TENANT_DOMAIN}"
paAdminApiPublicHostname: "pingaccess-admin-api.${PRIMARY_TENANT_DOMAIN}"
pawasAdminPublicHostname: "pingaccess-was-admin.${PRIMARY_TENANT_DOMAIN}"
pcAdminPublicHostname: "pingcentral-admin.${PRIMARY_TENANT_DOMAIN}"
pcAdminPrivateSiteHostname: "pingcentral.mulloway1.us1.ping-preview.cloud"
pdClusterPublicHostname: "pingdirectory-cluster.${PRIMARY_TENANT_DOMAIN}"
pfClusterPublicHostname: "pingfederate-cluster.${PRIMARY_TENANT_DOMAIN}"
paClusterPublicHostname: "pingaccess-cluster.${PRIMARY_TENANT_DOMAIN}"
pawasClusterPublicHostname: "pingaccess-was-cluster.${PRIMARY_TENANT_DOMAIN}"

# Ping engine hostname variables
pdPublicHostname: "pingdirectory-admin.${TENANT_DOMAIN}"
pdHttpPublicHostname: "pingdirectory.${TENANT_DOMAIN}"
pdDelegatorPublicHostname: "pingdelegator.${TENANT_DOMAIN}"
pdDelegatorPublicPort: 443
pfEnginePublicHostname: "pingfederate.${TENANT_DOMAIN}"
paEnginePublicHostname: "pingaccess.${TENANT_DOMAIN}"
pawasEnginePublicHostname: "pingaccess-was.${TENANT_DOMAIN}"

prometheusPublicHostname: "prometheus.${TENANT_DOMAIN}"
grafanaPublicHostname: "monitoring.${TENANT_DOMAIN}"
kibanaPublicHostname: "logs.${TENANT_DOMAIN}"
argocdPublicHostname: "argocd.${TENANT_DOMAIN}"

healthcheckHttpbinPawasPublicHostname: "healthcheck-httpbin-pa-was.${TENANT_DOMAIN}"
healthcheckHttpbinPaPublicHostname: "healthcheck-httpbin-pa.${TENANT_DOMAIN}"


#### FEATURE FLAGS #####################################################################################################
# Set to true to enable, most are disabled by default
# Please follow runbook instructions for the given feature flag to enable/disable

# !!! Provisioning for PingFederate is not yet available for multi-region customers !!!
# Runbook: https://confluence.pingidentity.com/display/PingCloud/How+to+Enable+and+Configure+PingFederate+Provisioning
pfProvisioningEnabled: false

radiusProxyEnabled: false
########################################################################################################################




########################################################################################################################
#TODO: Are these needed anymore now that we're using values files?
# If they are needed uncomment & move to the 1st section
# If they are still commented out when we get to PDO-4842, they will be deleted
########################################################################################################################
# kustomizeBase: prod/small

# ansibleBelugaImageTag: v1.18-release-branch-latest

# clusterNameLc: mulloway1 # Helm has a "lower" function that can be used with clusterName


########################################################################################################################
#TODO: Move these to app values.yaml files as apps migrate
# If they are needed by more than 1 app, move to the 1st section
########################################################################################################################
# pgoBackupBucketName is the customer-specific pgo bucket name for region
pgoBackupBucketName: "surajthapa-primary-backup-archives-bucket"

############################################################
# Platform event queue and SSM variables
############################################################
platformEventQueueName: "v2_platform_event_queue.fifo"
platformEventQueuePollBatchSize: 1
platformEventQueuePollIntervalSeconds: 2
orchAPISSMPathPrefix: "/pcpt/orch-api"
serviceSSMPathPrefix: "/pcpt/service"

############################################################
# Cluster state repo details
############################################################
# knownHostsClusterStateRepo is the known-hosts file to trust the cluster state repo server for git/ssh cloning
knownHostsClusterStateRepo: "|1|jdigV1dqpdayX1I7Z1dbr7GY49s=|1acUGQHUFxLztfMVH4u9avPqGK8= ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCNbmnXfe621xtVMkrwOqf6QNIlnOKkQ01KoM6gKC4nv5T08hbGcGp6iYplGLKMLlki+auO1J3JTA3qAKDobZR1wDqtW9LC2k46GHV4YigUpd6D+YdranJqbxpGOuNd6c1EP50vQnlW9MxZYExyrZKT0UfOJAydQLoWPuSioyHk3zAltSIrCxczP3jxAhuoq++eUrdC5uF6UMNJC10eBA9XglAe2oRLzApoStyCAiKVnoBndU2NpJWqNw0K5qfEUx2vyQFfHNRAwNNRDFtkdE9ho255YECTO07Zg37QCZ+hV5VAoFRu5CHSXqVZc5YN1YXkZ8SVHyBX7krO80QaaDor"

# clusterStateRepoUrl is the Cluster State Repo URL
clusterStateRepoUrl: "https://github.com/sura8257/ping-cloud-base"

# clusterStateRepoBranch is the Cluster State Repo branch
clusterStateRepoBranch: "stage"

# appResyncSeconds is the application reconciliation timeout in seconds for ArgoCD, i.e. how frequently
# ArgoCD should poll the cluster-state-repo for changes. To disable reconciliation set it to 0.
appResyncSeconds: 60

# Current app logs destination (True :  CW, False :  ELK)
legacyLogging: False

############################################################
# Lets Encrypt server
############################################################
letsEncryptServer: "https://acme-staging-v02.api.letsencrypt.org/directory"

############################################################
# PingFederate variables for environment
############################################################
pfPdBindPort: 1389
pfPdBindProtocol: "ldap"
pfPdBindUseSsl: false

pfMinHeap: 3072m
pfMaxHeap: 3072m
pfMinYgen: 1536m
pfMaxYgen: 1536m

# This variable's value will make it onto the branding for the PF admin console and
# will include the name of the environment and the region where it's deployed.
pfAdminConsoleEnvironment: "stage-us-east-2"

############################################################
# PingAccess variables for environment
############################################################
pawasMinHeap: 2048m
pawasMaxHeap: 2048m
pawasMinYgen: 1024m
pawasMaxYgen: 1024m
pawasGcoption: -XX:+UseParallelGC

paMinHeap: 1024m
paMaxHeap: 1024m
paMinYgen: 512m
paMaxYgen: 512m
paGcoption: -XX:+UseParallelGC

# Retention time for Prometheus. Could be set in years(y), weeks(w), days(d), hours(h), minutes(m) or seconds(s)
prometheusRetentionTime: "15d"

# Commands and schedules to obtain users count. Values should be in single quotes. Schedules should be in cron format. Command should return only numeric value(int\float)
prometheusUserCount1Command: 'echo 0'
prometheusUserCount1Schedule: '* * * * *'
prometheusUserCount2Command: 'echo 0'
prometheusUserCount2Schedule: '* * * * *'
prometheusUserCount3Command: 'echo 0'
prometheusUserCount3Schedule: '* * * * *'
prometheusUserCount4Command: 'echo 0'
prometheusUserCount4Schedule: '* * * * *'

# Variable to have ping-cloud namespace in prometheus-job-exporter
prometheusPingNamespace: "ping-cloud"

# Default argo-events notification configuration
notificationEnabled: false
slackChannel: "nowhere"
notificationEndpoint: "http://webhook-eventsource-svc.argo-events:12999/notification"

# Prometheus argo-events notification configuration
promNotificationEnabled: true
promSlackChannel: "nowhere"

# Variables used by argocd-image-updater to automatically update the container images managed by ArgoCD
imageTagPrefix: "v1"
imageList: "apps: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingfederate,apps: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingaccess,apps: public.ecr.aws/r2h3l6e4/pingcloud-apps/pingaccess-was"

# Dashboards repo variables
dashRepoUrl: "https://github.com/pingidentity/ping-cloud-dashboards"
dashRepoBranch: "v1.18-dev-branch"
