# Remove PingAccess primary-cluster resources
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-admin
$patch: delete

---

apiVersion: v1
kind: Service
metadata:
  name: pingaccess-admin
$patch: delete

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pingaccess-backup
$patch: delete

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-periodic-backup
$patch: delete

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-admin-periodic-csd-upload
$patch: delete

---

# Remove PingAccess WAS primary-cluster resources
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was-admin
$patch: delete

---

apiVersion: v1
kind: Service
metadata:
  name: pingaccess-was-admin
$patch: delete

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: pingaccess-was-admin-ingress
$patch: delete

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pingaccess-was-backup
$patch: delete

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingaccess-was-periodic-backup
$patch: delete

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
$patch: delete

---

# Remove PingFederate primary-cluster resources
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingfederate-admin
$patch: delete

---

apiVersion: v1
kind: Service
metadata:
  name: pingfederate-admin
$patch: delete

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: pingfederate-backup
$patch: delete

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingfederate-periodic-backup
$patch: delete

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingfederate-admin-periodic-csd-upload
$patch: delete

---

# Remove PingDirectory primary-cluster resources

apiVersion: v1
kind: ConfigMap
metadata:
  name: pingdirectory-backup
$patch: delete

---

apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: pingdirectory-periodic-backup
$patch: delete