apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingfederate-admin
spec:
  template:
    spec:
      initContainers:
      - name: pingfederate-discovery-service
        image: amazon/aws-cli:2.0.17
        imagePullPolicy: IfNotPresent
        command:
        - /get_ssm_env_vars.sh
        envFrom:
        - configMapRef:
            name: pingfederate-environment-variables
        volumeMounts:
        - name: data-dir
          mountPath: /config
        - name: discovery-service
          mountPath: /get_ssm_env_vars.sh
          subPath: get_ssm_env_vars.sh
      volumes:
      - name: discovery-service
        configMap:
          name: discovery-service
          defaultMode: 0555

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingfederate
spec:
  template:
    spec:
      initContainers:
      - name: pingfederate-discovery-service
        image: amazon/aws-cli:2.0.17
        imagePullPolicy: IfNotPresent
        command:
        - /get_ssm_env_vars.sh
        envFrom:
        - configMapRef:
            name: pingfederate-environment-variables
        volumeMounts:
        - name: data-dir
          mountPath: /config
        - name: discovery-service
          mountPath: /get_ssm_env_vars.sh
          subPath: get_ssm_env_vars.sh
      volumes:
      - name: discovery-service
        configMap:
          name: discovery-service
          defaultMode: 0555
