apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pgo-gp3
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
allowVolumeExpansion: true
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: ext4
  encrypted: "true"
  type: gp3