apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: pgo-gp2
parameters:
  encrypted: "true"
  fsType: ext4
  # Change to gp3 once PDO-4009 and dependencies are done
  type: gp2
# Revisit mountOptions/reclaimPolicy with PDO-4339
mountOptions:
  - discard
reclaimPolicy: Delete
provisioner: kubernetes.io/aws-ebs
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true