kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../../../../base/karpenter

patchesJson6902:

# Adjust the volume size for instances that will be provisioned by Karpenter.
patches:
  - target:
      kind: AWSNodeTemplate
      name: default
    patch: |-
      - op: replace
        path: /spec/blockDeviceMappings/0/ebs/volumeSize
        value: '120Gi'
  - target:
      kind: AWSNodeTemplate
      name: pd-only
    patch: |-
      - op: replace
        path: /spec/blockDeviceMappings/0/ebs/volumeSize
        value: '120Gi'
  - target:
      kind: AWSNodeTemplate
      name: pgo-only
    patch: |-
      - op: replace
        path: /spec/blockDeviceMappings/0/ebs/volumeSize
        value: '120Gi'

patchesStrategicMerge:
- |-
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: default
  spec:
    requirements:
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["c", "m", "r", "t"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["on-demand"]

- |-
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: pd-only
  spec:
    requirements:
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["c", "m", "r", "t"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["on-demand"]
      - key: kubernetes.io/os
        operator: In
        values:
        - linux

- |-
  apiVersion: karpenter.sh/v1alpha5
  kind: Provisioner
  metadata:
    name: pgo-only
  spec:
    requirements:
      - key: "karpenter.k8s.aws/instance-category"
        operator: In
        values: ["c", "m", "r", "t"]
      - key: "kubernetes.io/arch"
        operator: In
        values: ["amd64"]
      - key: "karpenter.sh/capacity-type"
        operator: In
        values: ["on-demand"]
      - key: kubernetes.io/os
        operator: In
        values:
          - linux
