#!/usr/bin/env sh

# Script to inject variables discovered by initContainer to .env file used by docker build hook scripts.

# Environment file generated by discovery service.
DISCOVERY_SERVICE_ENV_FILE='/opt/staging/ds_env_vars'

# Environment file used by docker build hook scripts.
DOCKER_BUILD_ENV_FILE='/opt/staging/.env'

echo "INFO: Check if ${DISCOVERY_SERVICE_ENV_FILE} exists"
if test -f "${DISCOVERY_SERVICE_ENV_FILE}"; then
  echo "INFO: Inject variable(s) in ${DISCOVERY_SERVICE_ENV_FILE} to ${DOCKER_BUILD_ENV_FILE}"
  cat ${DISCOVERY_SERVICE_ENV_FILE} >> ${DOCKER_BUILD_ENV_FILE}
else
  echo "WARNING: unable to locate ${DISCOVERY_SERVICE_ENV_FILE}"
fi

echo  "Execution completed successfully"

exit 0