apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: pingfederate-passwords
  annotations:
    sealedsecrets.bitnami.com/managed: "true"

---

apiVersion: v1
kind: Secret
metadata:
  name: pingfederate-license
  annotations:
    sealedsecrets.bitnami.com/managed: "true"
type: Opaque
