apiVersion: certmanager.k8s.io/v1alpha1
kind: Certificate
metadata:
  name: acme-tls-cert
  namespace: cert-manager
spec:
  secretName: acme-tls-cert
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - '*.ping-demo.com'
  commonName: ping-demo.com