apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingdirectory
spec:
  replicas: 3
  template:
    spec:
      containers:
      - name: pingdirectory
        resources:
          requests:
            memory: 64Gi
            cpu: 14
  volumeClaimTemplates:
  - metadata:
      name: out-dir
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: pingdirectory-gp2
      resources:
        requests:
          storage: 200Gi