kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: ingress-nginx-private
resources:
- ../base
- hpa.yaml
- cluster-role-binding.yaml
- validating-webhook-configuration.yaml

namespace: ingress-nginx-private

commonLabels:
  app.kubernetes.io/name: ingress-nginx
  app.kubernetes.io/part-of: ingress-nginx
  app.kubernetes.io/role: ingress-nginx-private

patchesJson6902:
- path: add-deployment-args.yaml
  target:
    group: apps
    version: v1
    kind: Deployment
    name: nginx-ingress-controller

- path: make-service-private.yaml
  target:
    version: v1
    kind: Service
    name: ingress-nginx
- target:
    kind: ClusterRole
    name: ingress-nginx
  options:
    allowNameChange: true
  patch: |-
    - op: replace
      path: /metadata/name
      value: ingress-nginx-private
- target:
    kind: ClusterRole
    name: ingress-nginx-admission
  options:
    allowNameChange: true
  patch: |-
    - op: replace
      path: /metadata/name
      value: ingress-nginx-admission-private
- target:
    kind: ServiceAccount
    name: ingress-nginx
  options:
    allowNameChange: true
  patch: |-
    - op: replace
      path: /metadata/name
      value: ingress-nginx-private
- target:
    kind: IngressClass
    name: nginx
  options:
    allowNameChange: true
  patch: |-
    - op: replace
      path: /metadata/name
      value: nginx-private
- target:
    kind: ClusterRoleBinding
    name: ingress-nginx
  options:
    allowNameChange: true
  patch: |-
    - op: replace
      path: /metadata/name
      value: ingress-nginx-private
- target:
    kind: ClusterRoleBinding
    name: ingress-nginx-admission
  options:
    allowNameChange: true
  patch: |-
    - op: replace
      path: /metadata/name
      value: ingress-nginx-admission-private
