kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- deployment.yaml
- service.yaml
- ingress.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingcloud-metadata-environment-variables
  envs:
  - env_vars
