# This defines the external ingress for the pingdelegator service

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pingdelegator-ext-ingress
  namespace: ${PING_CLOUD_NAMESPACE}
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    kubernetes.io/ingress.class: nginx-public
spec:
  tls:
  - hosts:
    - ext-pingdelegator.${DNS_ZONE}
  rules:
  - host: ext-pingdelegator.${DNS_ZONE}
    http:
      paths:
      - pathType: Prefix
        path: /
        backend:
          service:
            name: pingdelegator
            port:
              number: 1443