kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- secret.yaml
- configmap.yaml
- storage.yaml
- statefulset.yaml
- service.yaml
- ingress.yaml

commonLabels:
  role: pingdirectory

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: pingdirectory-environment-variables
  envs:
  - env_vars