apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pingaccess-was
spec:
  template:
    spec:
      containers:
      - name: pingaccess-was
        resources:
          limits:
            memory: 1Gi
            cpu: 1
          requests:
            memory: 1Gi
            cpu: 1
  replicas: 1