kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../base

generatorOptions:
  disableNameSuffixHash: false

configMapGenerator:

# Create the config maps that hold the variable for triggering updates of PD servers
- name: pingdirectory-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingdirectory/env_vars

# Create the config maps that hold the variable for triggering updates of PF servers
- name: pingfederate-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingfederate/env_vars

# Create the config maps that hold the variable for triggering updates of PA servers
- name: pingaccess-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingaccess/env_vars

# Create the config maps that hold the variable for triggering updates of PA WAS servers
- name: pingaccess-was-last-update-config
  namespace: ${PING_CLOUD_NAMESPACE}
  envs:
  - pingaccess-was/env_vars

# Pingdirectory
- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingdirectory/env_vars

# Pingfederate
- name: pingfederate-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingfederate/env_vars

# PingAccess
- name: pingaccess-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingaccess/env_vars

# PingAccess WAS
- name: pingaccess-was-environment-variables
  behavior: merge
  envs:
  - ../base/env_vars
  - env_vars
  - pingaccess-was/env_vars

patchesStrategicMerge:

### Regional enablement - remove admins, backups, etc. from secondary ###
### This patch should be commented out on the primary region ###
# - ../base/ping-cloud/remove-from-secondary-patch.yaml
