kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
# Apply PingAccess-WAS runtime engine deployment resources
- ${K8S_GIT_URL}/k8s-configs/ping-cloud/${KUSTOMIZE_BASE}/pingaccess-was/engine?ref=${K8S_GIT_BRANCH}

images:
- name: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingaccess-was${ECR_ENV}
  newName: ${ECR_REGISTRY_NAME}/pingcloud-apps/pingaccess-was${ECR_ENV}
  newTag: ${PINGACCESS_WAS_IMAGE_TAG}

patchesJson6902:

### PingAccess WAS Engine Last Update Config Map ###
- target:
    group: apps
    version: v1
    kind: StatefulSet
    name: pingaccess-was
  patch: |
    - op: add
      path: /spec/template/spec/containers/0/envFrom/-
      value:
        configMapRef:
          name: pingaccess-was-last-update-config

### Ingress patches ###

# PingAccess admin and PingFederate admin through PingAccess-WAS
- target:
    group: networking.k8s.io
    version: v1
    kind: Ingress
    name: pingaccess-was-ingress
  patch: |
    # PingAccess admin through PingAccess-WAS
    - op: remove
      path: /spec/tls/0/hosts/0
    - op: remove
      path: /spec/rules/0/host

    # PingFederate admin through PingAccess-WAS
    - op: remove
      path: /spec/tls/0/hosts/1
    - op: remove
      path: /spec/rules/1/host

    # Grafana to pingaccess was runtime
    - op: remove
      path: /spec/tls/0/hosts/2
    - op: remove
      path: /spec/rules/2/host

    # Prometheus to pingaccess was runtime
    - op: remove
      path: /spec/tls/0/hosts/3
    - op: remove
      path: /spec/rules/3/host

    # PingCentral console through PA-WAS engines
    - op: replace
      path: /spec/tls/0/hosts/0
      value: pingcentral-admin.${DNS_ZONE}
    - op: replace
      path: /spec/rules/0/host
      value: pingcentral-admin.${DNS_ZONE}

    # Healthcheck httpbin service through PA-WAS engines
    - op: remove
      path: /spec/tls/0/hosts/1
    - op: remove
      path: /spec/rules/1/host

    # Argo CD pingaccess was runtime
    - op: replace
      path: /spec/tls/0/hosts/1
      value: argocd.${DNS_ZONE}
    - op: replace
      path: /spec/rules/1/host
      value: argocd.${DNS_ZONE}
