apiVersion: v1
kind: ServiceAccount
metadata:
  name: ping-serviceaccount

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: ping-role
rules:
  - apiGroups:
    - ""
    resources:
    - "pods"
    - "pods/log"
    - "secrets"
    - "configmaps"
    verbs:
    - get
    - list
  - apiGroups:
    - ""
    resources:
    - "persistentvolumeclaims"
    verbs:
    - delete
  - apiGroups:
    - ""
    - "apps"
    - "extensions"
    resources:
    - "statefulsets"
    - "deployments"
    verbs:
    - get
    - list
    - watch
  - apiGroups:
    - ""
    resources:
    - "pods/exec"
    verbs:
    - create

---

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: ping-role-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ping-role
subjects:
  - kind: ServiceAccount
    name: ping-serviceaccount