kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ../base
- configmap.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:

- name: pingdirectory-environment-variables
  behavior: merge
  envs:
  - env_vars

patchesStrategicMerge:
- pingdirectory-tunnel.yaml

patchesJson6902:

# Expose the stunnel port on the headless service used for internal communication
- target:
    version: v1
    kind: Service
    name: pingdirectory
  patch: |-
    - op: add
      path: /spec/ports/-
      value:
        port: 5678
        name: stunnel
        targetPort: stunnel

# Point the pingdirectory load balancer to the stunnel port
- target:
    version: v1
    kind: Service
    name: pingdirectory-admin
  patch: |-
    - op: replace
      path: /spec/ports/0/targetPort
      value:
        stunnel