kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

resources:
- ${K8S_GIT_URL}/k8s-configs/cluster-tools/${KUSTOMIZE_BASE}/karpenter?ref=${K8S_GIT_BRANCH}

patchesStrategicMerge:

- |-
  apiVersion: v1
  kind: ConfigMap
  metadata:
    name: karpenter-global-settings
    namespace: karpenter
  data:
    "aws.clusterEndpoint": "${CLUSTER_ENDPOINT}"
    "aws.clusterName": "${CLUSTER_NAME}"

### Patch to add irsa annotations
- |-
  apiVersion: v1
  kind: ServiceAccount
  metadata:
    name: karpenter
    namespace: karpenter
    annotations:
      purpose: karpenter-provisioner
      ${KARPENTER_ROLE_ANNOTATION_KEY_VALUE}

