kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: argocd

resources:
- argo.yaml
- argocd-image-updater.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: install-custom-tools
  files:
  - install-custom-tools.sh
