apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  consolidation:
    enabled: true
  limits:
    resources:
      cpu: "400"
      memory: 400Gi
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
  providerRef:
    name: default
  labels:
    provisionerType: default
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: pgo-only
spec:
  annotations:
    karpenter.sh/do-not-consolidate: "true"
  limits:
    resources:
      cpu: "24"
      memory: 50Gi
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
  taints:
    - effect: NoSchedule
      key: pingidentity.com/pgo-only
      value: "true"
  providerRef:
    name: pgo-only
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: pd-only
spec:
  annotations:
    karpenter.sh/do-not-consolidate: "true"
  limits:
    resources:
      cpu: "64"
      memory: 500Gi
  requirements:
    - key: "kubernetes.io/arch"
      operator: In
      values: ["amd64"]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["on-demand"]
    - key: kubernetes.io/os
      operator: In
      values:
        - linux
  taints:
    - effect: NoSchedule
      key: pingidentity.com/pd-only
      value: "true"
  providerRef:
    name: pd-only
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: default
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 120Gi
        volumeType: gp3
        encrypted: true
  tags:
    KarpenerProvisionerName: "default"
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: pd-only
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 120Gi
        volumeType: gp3
        encrypted: true
  tags:
    KarpenerProvisionerName: "pd-only"
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: pgo-only
spec:
  metadataOptions:
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 2
    httpTokens: required
  blockDeviceMappings:
    - deviceName: /dev/xvda
      ebs:
        volumeSize: 120Gi
        volumeType: gp3
        encrypted: true
  tags:
    KarpenerProvisionerName: "pgo-only"
