kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: flux

resources:
- flux.yaml

patchesStrategicMerge:
- patch-flux-deployment.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- name: flux-command
  files:
  - flux-command.sh